name: Mirror

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --bare https://github.com/litetex/fdroid-pages.git --single-branch --branch gh-pages
          cd fdroid-pages.git
          echo "Renaming branch"
          git branch -m gh-pages pages
          echo "Starting push"
          git push --mirror https://litetex:${{ secrets.CB_TOKEN }}@codeberg.org/litetex/fdroid-pages.git
          echo "Done"
